### PR TITLE
fix: access denied page layout

### LINKED ISSUE #232: insufficient permission warning overlap the nav bar
## Summary

The nav bar is overlapped by the warning message. The user can not logout the current user to switch another user.

## Steps to reproduce

1. login the web console with a user without operator and analyst permissions

## What is the current bug behavior?

see below screenshot

## Relevant logs and/or screenshots

image

## Possible fixes

---

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by tyyzqmf**
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

## Summary

close #232 

## Implementation highlights

(describe how the merge request does for feature changes, share the RFC link if it has)

## Test checklist

- [ ] add new test cases
- [ ] all code changes are covered by unit tests
- [ ] end-to-end tests
  - [ ] deploy web console with CloudFront + S3 + API gateway
  - [ ] deploy web console within VPC
  - [ ] deploy ingestion server
    - [ ] with MSK sink
    - [ ] with KDS sink
    - [ ] with S3 sink
  - [ ] deploy data processing
  - [ ] deploy data modeling
    - [ ] new Redshift Serverless
    - [ ] provisioned Redshift
    - [ ] Athena
  - [ ] deploy with reporting

## Is it a breaking change

- [ ] add parameters without default value in stack
- [ ] introduce new service permission in stack
- [ ] introduce new top level stack module

## Miscellaneous

- [ ] introduce new symbol link source file(s) to be shared among infra code, web console frontend, and web console backend

### CODE REVIEW

File: frontend/src/components/common/RoleRoute.tsx [hunk 1]
```diff
@@ -37,7 +37,11 @@ const RoleRoute = ({
   );
 
   if (!userHasRequiredRole) {
-    return <AccessDenied />;
+    return (
```
Comment (chenhaiyun) [inline frontend/src/components/common/RoleRoute.tsx:40]: Do we have **Analytics** Access Denied Page?

Comment (tyyzqmf) [reply frontend/src/components/common/RoleRoute.tsx:47]: added.

**Review by chenhaiyun — APPROVED** [review]
